# longtou.2024
FROM gcr.io/deeplearning-platform-release/pytorch-cu121.2-3.py310

RUN apt update && apt install -y parallel file cmake espeak-ng sox libsox-fmt-all
WORKDIR /root
ADD Montreal-Forced-Aligner /root/Montreal-Forced-Aligner
WORKDIR /root/Montreal-Forced-Aligner
RUN ./setup_miniforge.sh conda mfa 3.11
# 인증 문제때문에 실행하기 어려우므로 직접 복사
#RUN git submodule update --init --recursive
RUN . ./activate_python.sh && pip install uv
RUN  . ./activate_python.sh  && conda env update -f environment.yml && uv pip install -e .
RUN . ./activate_python.sh && uv pip install -r requirements.txt
ENV PATH="/root/Montreal-Forced-Aligner/conda/envs/mfa/bin:/root/Montreal-Forced-Aligner/conda/condabin:$PATH"

CMD ["/bin/bash"]
